AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyPostgreSQLDB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      DBInstanceIdentifier: ods-1
      MasterUsername: myusername
      MasterUserPassword: mypassword
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      VPCSecurityGroups:
        - !Ref MySecurityGroup
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      PubliclyAccessible: true
